attach(Computer)
Computer <- read.csv("E:/Datasets/Multi linear Regression/Computer_Data (1).csv")
View(Computer)
install.packages("e1071")
library(e1071)
install.packages("carData")
library(car)
library(psych)
Computer<-Computer[,-1]
View(Computer) 
str(Computer)
summary(Computer)
describe(Computer)
t <- is.na(Computer)
unique_cd <- unique(Computer$cd)
Computer$cd = factor(Computer$cd,
                          levels = c(unique_cd),
                          labels = c(1,0))
unique_multi <- unique(Computer$multi)
unique(Computer$multi)
Computer$multi = factor(Computer$multi,
                             levels = c(unique_multi),
                             labels = c(1,0))

unique_premium <- unique(Computer$premium)
unique(Computer$premium)
Computer$premium = factor(Computer$premium,
                               levels = c(unique_premium),
                               labels = c(1,0))

Computer$cd<-as.numeric(as.character(Computer$cd))
Computer$multi<-as.numeric(as.character(Computer$multi))
Computer$premium<-as.numeric(as.character(Computer$premium))
View(Computer)
str(Computer)
model <- lm(price ~ ., data = Computer)
summary(model)
install.packages("carTools")
library(carTools)
pairs(Computer)
cor(Computer)
install.packages("car")
library(car)
car::vif(model)
library(MASS)
stepAIC(model)
plot(model)
residualPlots(model)
avPlots(model)  
qqPlot(model)
influenceIndexPlot(model)
model1<-lm(price~speed+log(hd)+ram+screen+premium+trend,data=Computer)
summary(model1)
car::vif(model1)
library(MASS)
stepAIC(model1)
plot(model1)
residualPlots(model1)
avPlots(model1)
qqPlot(model1)
influenceIndexPlot(model1)
modelf<-lm(log(price)~speed+log(hd)+ram+screen+premium+trend,data=Computer[-c(1441,1701),])
summary(modelf)
car::vif(modelf)
library(MASS)
stepAIC(modelf)
graphics.off()
par(mar=c(2,2,2,2))
plot(modelf)
residualPlots(modelf)
avPlots(modelf)
qqPlot(modelf)
influenceIndexPlot(modelf,id.n=3)


