data <- read.csv("E:\\Datasets\\PCA Dimension Reduction\\wine.csv")
View(mydata)
library(ggplot2)
library(dplyr)
library(MASS)
library(car)
library(caTools)
library(stats)
library(ggfortify)
library(cluster)
summary(mydata)
mydata<- scale(mydata[,-1])
install.packages("MFPCA")
library(MFPCA)
install.packages("funData")
library(funData)
pcaObj <- princomp(mydata[1:178,1:13],cor=TRUE,scores=TRUE,covmat = NULL)
summary(pcaObj)
help(princomp)
svdObj <- svd(mydata[1:178,1:13],nu = nrow(mydata),nv= ncol(mydata))
summary(svdObj)
svdObj$d
svdObj$v
biplot(svdObj$u,svdObj$v)
?biplot
screeplot(pcaObj)
loadings(pcaObj)
biplot(pcaObj)
pcaObj$scores
pcaObj$scores[,1:3]
mydata<-cbind(mydata,pcaObj$scores[,1:3])
data <- cbind(data,pcaObj$scores[,1:3])

View(mydata)
dist <- dist(mydata,method="euclidean")
hclustPca <- hclust(dist,method="complete")
plot(hclustPca)
groups <- cutree(hclustPca,k=9)
final <- cbind(mydata,groups)
View(final)
View(final[,-c(14:17)])
meanPca<-View(aggregate(final[,-c(14:17)],by=list(groups),FUN=mean))
wssplot<- function(data,nc=15,seed=1234){
  wss<- (nrow(data)-1) * sum(apply(data,2,var))
  for(i in 1:nc)
    {
    set.seed(seed)
    wss[i] <- sum(kmeans(data,centers=i)$withinss)
    }
    plot(1:nc,wss,type="b",xlab="no of clusters",ylab="Within sum of squares")
}    
wssplot(mydata)
km <- kmeans(mydata,9)
str(km)
autoplot(km,mydata,frame=TRUE)
View(data)
hso<- scale(data[,-1])
dist <- dist(hso,method="euclidean")
hclustPca <- hclust(dist,method="complete")
plot(hclustPca)
groups <- cutree(hclustPca,k=9)
finalhso <- cbind(hso,groups)
View(finalhso)
meanPcahso<-View(aggregate(finalhso,by=list(groups),FUN=mean))
wssplot(hso)
km <- kmeans(hso,9)
str(km)
autoplot(km,hso,frame=TRUE)
install.packages("animation")
library(animation)
kani <- kmeans.ani(hso,9)
